version: "3"
services:
  web:
    build: .
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/www
    ports:
      - "8002:8002"
    links:
      - redis
  redis:
    image: redis:latest

